Introduce tunnel proxy
nymea/nymea-remoteproxy pull request #23
Opened 2021-08-12 12:01 UTC by t-mon

2021-08-14 19:45 UTC, mzanetti requested changes

2021-08-14 19:45 UTC, mzanetti commented on libnymea-remoteproxy/server/tcpsocketserver.cpp
> +    qCWarning(dcTcpSocketServer()) << "Socket error occured" << error;
occurred

2021-08-14 19:45 UTC, mzanetti commented on libnymea-remoteproxyclient/tcpsocketconnection.cpp
> +    qCWarning(dcRemoteProxyClientTcpSocket()) << "Socket error occured" << error << m_tcpSocket->errorString();
occurred

2021-08-14 19:45 UTC, mzanetti commented on libnymea-remoteproxyclient/tcpsocketconnection.cpp
> +    qCWarning(dcRemoteProxyClientTcpSocket()) << "Socket error occured" << error << m_tcpSocket->errorString();
There are tons of those, please grep the code

2021-12-16 14:26 UTC, mzanetti commented
../../../nymea-app/libnymea-app/connection/tunnelproxytransport.cpp: In member function ‘virtual NymeaTransportInterface::ConnectionState TunnelProxyTransport::connectionState() const’:
../../../nymea-app/libnymea-app/connection/tunnelproxytransport.cpp:86:1: warning: control reaches end of non-void function [-Wreturn-type]
   86 | }
      | ^

2022-03-08 14:04 UTC, mzanetti requested changes
Do we need the flow doc as png, svg and txt?

Please exclude the docs folder from the dpkg source package, unless you have a -docs package that ships them.

2022-03-09 06:58 UTC, t-mon commented on client/main.cpp
> +    if (parser.isSet(tcpOption)) {
yes, the switch to default TCP everywhere is still missing, but should be a small one.

2022-03-09 06:59 UTC, t-mon commented on common/slipdataprocessor.h
> +* Copyright 2013 - 2021, nymea GmbH
actually, I update the copyright to the year of writing the code, not releasing, maybe we should align that

2022-03-09 07:08 UTC, t-mon commented on libnymea-remoteproxyclient/tunnelproxy/tunnelproxysocket.h
> +    bool m_connected = true; // Note: on creatrion, the socket is connected, otherwise it would not have been created
Offering that method would allow anybody to set the property only the socket or the server are allowed to change the connected state, therefore: I need the property to inform about the state (and having the signal and get method), but as user of the class you should not be able to set the variable. The `setConnected` method would also require to be private, so I see no point in that. Set disconnected on the other hand is a method because it does more than just updating a property.

2022-03-09 07:25 UTC, t-mon commented on nymea-remoteproxy.pro
> +    message("Building with ccache support")
well, depends on how you use it. There is the ccache option for qmake in the pri. If you use that option, you can explicitly enable ccache if you want without messing around with the system profile, and if you do so, you get informed here, once, not 10 times for each pro file in the project.

2022-03-09 07:36 UTC, t-mon commented on server/main.cpp
> +    QString timeString = QDateTime::currentDateTimeUtc().toString("yyyy.MM.dd hh:mm:ss.zzz");
well...in the logfile I don't wanna think about timezones...the server might be anywhere and when i have to check the logs, I don't have to calculate or thing about timezones matching maybe some app or core logs. The other solution would be (which also might be the case in 99%) having the servers system timezone to UTC...but when I read logs...I don't wanna care about that...probably better to remove it here or only add the timestamp if logging into a dedicated log file.

2022-03-09 14:02 UTC, t-mon commented on libnymea-remoteproxy/server/transportclient.cpp
> +    return QDateTime::fromMSecsSinceEpoch(creationTime() * 1000).toString("dd.MM.yyyy hh:mm:ss");
the int is actually required in the code logic (so i don't need to convert it all the time to ms since epoc / 1000), and the string is fine in localtime since it gets used only for debug purpose...so work as intended

2022-03-09 14:17 UTC, t-mon commented on libnymea-remoteproxy/tunnelproxy/tunnelproxyclient.cpp
> +        if (m_dataBuffer.trimmed().endsWith("}")) {
Well, I do it the same way as we do it in nymea, maybe we find a more elegant solution: https://github.com/nymea/nymea/blob/master/libnymea-core/jsonrpc/jsonrpcserverimplementation.cpp#L624

2022-03-09 14:32 UTC, t-mon commented on libnymea-remoteproxyclient/tcpsocketconnection.cpp
>      } else {
try ssl unless explictly disabled was the thought...

2022-03-09 14:44 UTC, t-mon commented on libnymea-remoteproxy/server/transportclient.h
> +    quint64 m_txDataCount = 0;
Agreed some can be private, but some make totally sense being protected. Fixed.

2022-03-10 16:36 UTC, mzanetti approved these changes

2022-03-29 15:23 UTC, closed without merging