Tcp server
nymea/nymea-remoteproxy pull request #9
Opened 2019-06-07 14:34 UTC by t-mon

2019-06-17 12:07 UTC, mzanetti commented on libnymea-remoteproxy/authentication/authenticationreply.cpp
> +    qCCritical(dcAuthentication()) << "Destroy authentication reply";
drop that

2019-06-17 12:12 UTC, mzanetti commented on libnymea-remoteproxy/jsonrpcserver.cpp
> +        return;
IMHO this isn't nice... bufferSizeViolation() is checked for >= 10KB inside proxyClient, yet the actual decision whether to disconnect it or not, and even worse the debug print for what the size limit is, is made in the server... It should either be:

if (proxyClient->bufferSize() >= 10KB) {
  qCWarning() << ...;
  proxyClient->kill(...);
}

or just

proxyClient->validateOrKill();

and all the magic for it is inside proxyClient.... But don't distribute a single logic across different classes.

2019-06-27 13:28 UTC, mzanetti commented
Observing occational test failures.

`FAIL!  : RemoteProxyOfflineTests::tcpRemoteConnection() 'remoteConnectionDataTwo.count() == 1' returned FALSE. ()
   Loc: [nymea-remoteproxy-tests-offline.cpp(1255)]`

2019-07-01 13:03 UTC, mzanetti commented
Crashes on incoming connections:

`Jul 01 13:02:02 nymea nymead[1244]:  I | AWS: Proxy remote connection request received
Jul 01 13:02:02 nymea nymead[1244]:  I | Cloud: Connecting to remote proxy server "wss://remoteproxy.nymea.io"
Jul 01 13:02:02 nymea nymead[1244]:  I | RemoteProxyClientConnection: Creating a web socket connection to "wss://remoteproxy.nymea.io"
Jul 01 13:02:02 nymea nymead[1244]:  I | RemoteProxyClientConnection: Connecting to "wss://remoteproxy.nymea.io"
Jul 01 13:02:02 nymea nymead[1244]:  I | RemoteProxyClientWebSocket: Connecting to "wss://remoteproxy.nymea.io"
Jul 01 13:02:02 nymea nymead[1244]:  I | RemoteProxyClientWebSocket: Socket state changed QAbstractSocket::ConnectingState
Jul 01 13:02:02 nymea nymead[1244]:  W | Application: Cought SIGSEGV signal. Segmentation fault!
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "[1] /lib/arm-linux-gnueabihf/libc.so.6"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "    ()+0x25750"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "    ??:0"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "[2] /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "    QMetaObject::indexOfEnumerator(char const*) const+0x2d"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "    ??:0"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "[3] /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "    qt_QMetaEnum_debugOperator(QDebug&, int, QMetaObject const*, char const*)+0x2f"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "    ??:0"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "[4] /usr/lib/arm-linux-gnueabihf/libnymea-remoteproxyclient.so.1"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "    remoteproxyclient::RemoteProxyConnection::setState(remoteproxyclient::RemoteProxyConnection::State)+0xb7"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "    ??:0"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "[5] /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "    QMetaObject::activate(QObject*, int, int, void**)+0x4b9"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "    ??:0"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "[6] /usr/lib/arm-linux-gnueabihf/libnymea-remoteproxyclient.so.1"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "    remoteproxyclient::ProxyConnection::stateChanged(QAbstractSocket::SocketState)+0x25"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "    ??:0"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "[7] /usr/lib/arm-linux-gnueabihf/libnymea-remoteproxyclient.so.1"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "    remoteproxyclient::WebSocketConnection::onStateChanged(QAbstractSocket::SocketState)+0x35"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "    ??:0"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "[8] /usr/lib/arm-linux-gnueabihf/libnymea-remoteproxyclient.so.1"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "    ()+0x178d6"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "    ??:0"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "[9] /usr/lib/arm-linux-gnueabihf/libQt5Core.so.5"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "    QMetaObject::activate(QObject*, int, int, void**)+0x40f"
Jul 01 13:02:02 nymea nymead[1244]:  C | Application: "    ??:0"
Jul 01 13:02:03 nymea systemd[1]: nymead.service: Main process exited, code=dumped, status=11/SEGV
Jul 01 13:02:03 nymea systemd[1]: nymead.service: Failed with result 'core-dump'.
`

2021-09-02 12:07 UTC, mzanetti requested changes

2021-09-03 06:28 UTC, t-mon commented on debian/rules
> +
dropped in #23

2022-03-02 22:57 UTC, mzanetti requested changes

2022-03-02 22:57 UTC, mzanetti commented on libnymea-remoteproxy/proxyclient.cpp
> +    }
Considering this input buffer:

`{ "id": 1, ... }\n{ "id": 2, "someMap": { "a": "b" }` split `}\n`

Wouldn't it return the packet 2 in the buffer even though it's not complete yet?

I guess 232 shouldn't trim the buffer and check for `endsWith("}\n")` instead?

2022-03-02 22:57 UTC, mzanetti commented on libnymea-remoteproxyclient/proxyjsonrpcclient.cpp
> +    }
Why is this code here a second time?
ProxyClient::processData() and JsonRpcClient::processData(), doing the same thing

2022-03-02 22:57 UTC, mzanetti commented on libnymea-remoteproxy/proxyclient.cpp
> +    return packages;
Package / packet

2022-03-02 22:57 UTC, mzanetti commented on libnymea-remoteproxy/proxyclient.h
> +    bool m_bufferSizeViolation = false;
defined but not used

2022-03-02 22:57 UTC, mzanetti commented on libnymea-remoteproxy/tcpsocketserver.h
> +*  Copyright 2013 - 2020, nymea GmbH
22

2022-03-02 22:57 UTC, mzanetti commented on libnymea-remoteproxy/tcpsocketserver.h
> +     QHash<QUuid, QTcpSocket *> m_clientList;
` `

2022-03-02 22:57 UTC, mzanetti commented on libnymea-remoteproxy/websocketserver.cpp
> +        qCWarning(dcWebSocketServer()) << "Next pending connection dissapeared. Doing nothing.";
disappeared (or vanished)

2022-03-02 22:57 UTC, mzanetti commented on libnymea-remoteproxy/websocketserver.cpp
> +    // Note: on any error which can occure, make sure the socket will be closed in any case
occur

2022-03-02 22:57 UTC, mzanetti commented on libnymea-remoteproxy/websocketserver.cpp
> +    qCDebug(dcWebSocketServer()) << "Stop server" << m_server->serverName() << serverUrl().toString();
Stopping

2022-03-02 22:57 UTC, mzanetti commented on libnymea-remoteproxyclient/proxyjsonrpcclient.cpp
> +void JsonRpcClient::processDataPackage(const QByteArray &data)
packet

2022-03-02 22:57 UTC, mzanetti commented on nymea-remoteproxy.pri
>             SERVER_VERSION_STRING=\\\"$${SERVER_VERSION}\\\" \
Would be nicer to use a config.in file for this, as passing DEFINES will invalidate the entire compiler cache each time you switch a branch with a different version.

Would be just creating a version.in.h file with  `#define SERVER_VERSION_STRING '"$$SERVER_VERSION_STRING"'`

and use `QMAKE_SUBSTITUTES += version.h.in` here
 Then include version.h where the string is needed and ccache will only recompile that one file

2022-03-02 22:57 UTC, mzanetti commented on server/main.cpp
> +                                             "Copyright %3 2021 nymea GmbH <developer@nymea.io>\n")
22

2022-03-02 22:57 UTC, mzanetti commented on tests/test-offline/nymea-remoteproxy-tests-offline.cpp
> +//void RemoteProxyOfflineTests::apiBasicCallsTcp_data()
not finished yet?

2022-03-29 10:28 UTC, merged